ALTER TABLE trails ADD COLUMN IF NOT EXISTS latitude NUMERIC(8,5);
ALTER TABLE trails ADD COLUMN IF NOT EXISTS longitude NUMERIC(8,5);
UPDATE trails SET latitude = 30.39, longitude = -97.67 WHERE name = 'BCGB - East';
UPDATE trails SET latitude = 30.39, longitude = -97.70 WHERE name = 'BCGB - West';
UPDATE trails SET latitude = 29.92, longitude = -96.88 WHERE name = 'Bluff Creek Ranch';
UPDATE trails SET latitude = 30.51, longitude = -97.77 WHERE name = 'Brushy - 1/4 Notch';
UPDATE trails SET latitude = 30.51, longitude = -97.77 WHERE name = 'Brushy - Double Down';
UPDATE trails SET latitude = 30.52, longitude = -97.82 WHERE name = 'Brushy - Peddlers';
UPDATE trails SET latitude = 30.51, longitude = -97.80 WHERE name = 'Brushy - Suburban Ninja';
UPDATE trails SET latitude = 30.51, longitude = -97.83 WHERE name = 'Brushy - West';
UPDATE trails SET latitude = 30.37, longitude = -97.78 WHERE name = 'Bull Creek';
UPDATE trails SET latitude = 30.32, longitude = -97.79 WHERE name = 'Cat Mountain';
UPDATE trails SET latitude = 30.34, longitude = -97.85 WHERE name = 'Emma Long';
UPDATE trails SET latitude = 29.97, longitude = -98.91 WHERE name = 'Flat Rock Ranch';
UPDATE trails SET latitude = 30.67, longitude = -97.72 WHERE name = 'Lake Georgetown';
UPDATE trails SET latitude = 30.36, longitude = -97.98 WHERE name = 'Lakeway';
UPDATE trails SET latitude = 30.17, longitude = -97.80 WHERE name = 'Mary Moore Searight';
UPDATE trails SET latitude = 30.26, longitude = -97.80 WHERE name = 'Maxwell Trail';
UPDATE trails SET latitude = 30.19, longitude = -97.77 WHERE name = 'McKinney Falls';
UPDATE trails SET latitude = 30.42, longitude = -98.10 WHERE name = 'Mule Shoe';
UPDATE trails SET latitude = 30.47, longitude = -98.02 WHERE name = 'Pace Bend';
UPDATE trails SET latitude = 30.44, longitude = -97.62 WHERE name = 'Pedernales Falls';
UPDATE trails SET latitude = 30.37, longitude = -98.12 WHERE name = 'Reimers Ranch';
UPDATE trails SET latitude = 30.01, longitude = -97.16 WHERE name = 'Rocky Hill Ranch';
UPDATE trails SET latitude = 30.27, longitude = -97.76 WHERE name = 'SATN - east of mopac';
UPDATE trails SET latitude = 30.28, longitude = -97.80 WHERE name = 'SATN - west of mopac';
UPDATE trails SET latitude = 30.23, longitude = -97.76 WHERE name = 'St. Edwards';
UPDATE trails SET latitude = 30.42, longitude = -97.62 WHERE name = 'Thumper';
UPDATE trails SET latitude = 30.40, longitude = -97.67 WHERE name = 'Walnut Creek'
